openapi: 3.0.3
info:
  title: VDES Callback API
  version: '1.0'
  description: >-
    The VDES API is an interface to be used for transmission and reception of messages via the MARIOT System. The interface consist of two parts: a Gateway part to be used by VDES services for transmission of unicast and broadcast packets via the system and a callback part that VDES services has to implement such that the gateway can relay packets from terminals/ships. This specification describes the callback part.
  contact:
    name: Sternula
    url: 'https://www.sternula.com'
tags:
  - name: Packet Reception
    description: Forward packets received from VDES terminals
paths:
  /packet:
    post:
      tags:
        - Packet Reception
      summary: Forward packets received from VDES terminals to the service
      description: 'Used by Gateway to deliver packets received from VDES terminals to a destination service'
      operationId: receiveVDESPacket
      parameters:
        - name: srcMMSI
          in: header
          required: true
          description: MMSI of sender
          schema:
            type: integer
          example: 123456789
        - name: dstMMSI
          in: header
          required: true
          description: MMSI of receiver
          schema:
            type: integer
          example: 987654321
        - name: rxTime
          in: header
          required: true
          description: >-
            Time when packet was received by the gateway
          schema:
            type: string
            format: date-time
          examples:
            oneId:
              summary: 'November 5, 1994, 13:15:30 UTC'
              value: '1994-11-05T13:15:30Z'
        - name: packetId
          in: header
          required: true
          description: >-
            Id to be used for identification of a packet for debugging and billing purposes
          schema:
            $ref: '#/components/schemas/PacketId'
          example: '12345678'
      requestBody:
        description: 'The request body contains the packet received from the VDES terminal'
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
              example: Any sequence of octets
      responses:
        '200':
          description: Successful response. Note that the response will not be forwarded to the sender of the message. If an acknowledgement is needed the MCP service must sent this in a message to the VDES terminal.
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /state:              
    post:
      tags:
        - Packet State
      summary: Update the state of packets that have been sent
      description: 'Used by Gateway to deliver packets received from VDES terminals to a destination service'
      operationId: receiveVDESPacketState
      parameters:
        - name: packetId
          in: header
          required: true
          description: The packet for which the state has changed
          schema:
            type: integer
          example: 123456789
        - name: state
          in: header
          required: true
          description: State of packetId
          schema:
            type: string
          example: "packet_delivered"

      requestBody:
        description: 'The request body is empty'
        content:
          application/*:
            schema:
              type: string
              format: string
              example: 
      responses:
        '200':
          description: Successful response. Note that the response will not be forwarded to the sender of the message. If an acknowledgement is needed the MCP service must sent this in a message to the VDES terminal.
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Error:
      type: object
      description: To be returned on error. Includes error code and optionally a description of the error.
      properties:
        errorCause:
          type: string
          enum: [unspecified, authentication_failure, invalid_service]
        errorMessage:
          type: string
      required:
        - errorCause
    PacketId:
      type: integer
      format: int64
security:
  - BasicAuth: []
